[package]

name = "lettre_email"
version = "0.7.1"
description = "Email builder"
readme = "README.md"
documentation = "https://docs.rs/lettre_email/"
repository = "https://github.com/lettre/lettre"
license = "MIT"
authors = ["Alexis Mousset <contact@amousset.me>"]
categories = ["email"]
keywords = ["email", "mailer"]

[badges]
travis-ci = { repository = "lettre/lettre_email" }

[dev-dependencies]
env_logger = "*"
lettre = { path = "../lettre", features = ["smtp-transport"] }

[dependencies]
email = "^0.0"
mime = "^0.3"
time = "^0.1"
lettre = { path = "../lettre", default-features = false }
uuid = { version = ">=0.4, <0.8", features = ["v4"] }
